# Generated by Django 4.1.4 on 2023-01-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
